[info]
game-name = "tpgzw"
full-game-name = "Twilight Princess Practice Rom"
developer-name = "Twilight Princess Community"
full-developer-name = "Speedrun Community"

[src]
iso = "rzde01_iso/DATA"
patch = "patch.asm"
map = "map/Rfinal/Release/RframeworkF.map"

[build]
map = "build/RZDE01.map"
iso = "build/rzde01_iso/DATA"

[link]
entries = ["game_loop", "read_controller", "draw", "init"]
base = "0x80560000"
libs = ["tpgzw.a", "external/libtpw_c/libtpw_c.a", "external/gcn_c/gcn_c.a"]

[files]
"tpgzw/save_files/any/aeralfos_skip.bin" = "res/save_files/any/aeralfos_skip.bin"
"tpgzw/save_files/any/boss_bug.bin" = "res/save_files/any/boss_bug.bin"
"tpgzw/save_files/any/camp.bin" = "res/save_files/any/camp.bin"
"tpgzw/save_files/any/death_sword_skip.bin" = "res/save_files/any/death_sword_skip.bin"
"tpgzw/save_files/any/deku_toad.bin" = "res/save_files/any/deku_toad.bin"
"tpgzw/save_files/any/early_platform.bin" = "res/save_files/any/early_platform.bin"
"tpgzw/save_files/any/fan_tower.bin" = "res/save_files/any/fan_tower.bin"
"tpgzw/save_files/any/forest_bit.bin" = "res/save_files/any/forest_bit.bin"
"tpgzw/save_files/any/goats.bin" = "res/save_files/any/goats.bin"
"tpgzw/save_files/any/gorge_void.bin" = "res/save_files/any/gorge_void.bin"
"tpgzw/save_files/any/hugo.bin" = "res/save_files/any/hugo.bin"
"tpgzw/save_files/any/lakebed_bk_skip.bin" = "res/save_files/any/lakebed_bk_skip.bin"
"tpgzw/save_files/any/mdh_bridge.bin" = "res/save_files/any/mdh_bridge.bin"
"tpgzw/save_files/any/mdh_tower.bin" = "res/save_files/any/mdh_tower.bin"
"tpgzw/save_files/any/norgor.bin" = "res/save_files/any/norgor.bin"
"tpgzw/save_files/any/onebomb.bin" = "res/save_files/any/onebomb.bin"
"tpgzw/save_files/any/pillar_clip.bin" = "res/save_files/any/pillar_clip.bin"
"tpgzw/save_files/any/poe_1_skip.bin" = "res/save_files/any/poe_1_skip.bin"
"tpgzw/save_files/any/stallord.bin" = "res/save_files/any/stallord.bin"
"tpgzw/save_files/any/purple_mist.bin" = "res/save_files/any/purple_mist.bin"
"tpgzw/save_files/any/ordon_gate_clip.bin" = "res/save_files/any/ordon_gate_clip.bin"
"tpgzw/save_files/any/ems.bin" = "res/save_files/any/ems.bin"
"tpgzw/save_files/any/forest_escape.bin" = "res/save_files/any/forest_escape.bin"
"tpgzw/save_files/any/lanayru_gate_clip.bin" = "res/save_files/any/lanayru_gate_clip.bin"
"tpgzw/save_files/any/karg.bin" = "res/save_files/any/karg.bin"
"tpgzw/save_files/any/eldin_twilight.bin" = "res/save_files/any/eldin_twilight.bin"
"tpgzw/save_files/any/iza.bin" = "res/save_files/any/iza.bin"
"tpgzw/save_files/any/spr_warp.bin" = "res/save_files/any/spr_warp.bin"
"tpgzw/save_files/any/spr.bin" = "res/save_files/any/spr.bin"
"tpgzw/save_files/any/lakebed_1.bin" = "res/save_files/any/lakebed_1.bin"
"tpgzw/save_files/any/lakebed_2.bin" = "res/save_files/any/lakebed_2.bin"
"tpgzw/save_files/any/ag.bin" = "res/save_files/any/ag.bin"
"tpgzw/save_files/any/cits_early.bin" = "res/save_files/any/cits_early.bin"
"tpgzw/save_files/any/cits_1.bin" = "res/save_files/any/cits_1.bin"
"tpgzw/save_files/any/cits_2.bin" = "res/save_files/any/cits_2.bin"
"tpgzw/save_files/any/argorok.bin" = "res/save_files/any/argorok.bin"
"tpgzw/save_files/any/palace_1.bin" = "res/save_files/any/palace_1.bin"
"tpgzw/save_files/any/palace_2.bin" = "res/save_files/any/palace_2.bin"
"tpgzw/save_files/any/zant.bin" = "res/save_files/any/zant.bin"
"tpgzw/save_files/any/hc.bin" = "res/save_files/any/hc.bin"
"tpgzw/save_files/any/hc_tower.bin" = "res/save_files/any/hc_tower.bin"
"tpgzw/save_files/any/darknut.bin" = "res/save_files/any/darknut.bin"
"tpgzw/save_files/any/darkhammer.bin" = "res/save_files/any/darkhammer.bin"
"tpgzw/save_files/any/beast_ganon.bin" = "res/save_files/any/beast_ganon.bin"
"tpgzw/save_files/any/horseback_ganon.bin" = "res/save_files/any/horseback_ganon.bin"
"tpgzw/save_files/any/lanayru_twilight.bin" = "res/save_files/any/lanayru_twilight.bin"
"tpgzw/save_files/hundo/aeralfos_skip.bin" = "res/save_files/hundo/aeralfos_skip.bin"
"tpgzw/save_files/hundo/boss_bug.bin" = "res/save_files/hundo/boss_bug.bin"
"tpgzw/save_files/hundo/camp.bin" = "res/save_files/hundo/camp.bin"
"tpgzw/save_files/hundo/death_sword_skip.bin" = "res/save_files/hundo/death_sword_skip.bin"
"tpgzw/save_files/hundo/deku_toad.bin" = "res/save_files/hundo/deku_toad.bin"
"tpgzw/save_files/hundo/early_platform.bin" = "res/save_files/hundo/early_platform.bin"
"tpgzw/save_files/hundo/fan_tower.bin" = "res/save_files/hundo/fan_tower.bin"
"tpgzw/save_files/hundo/faron_twilight.bin" = "res/save_files/hundo/faron_twilight.bin"
"tpgzw/save_files/hundo/forest_bit.bin" = "res/save_files/hundo/forest_bit.bin"
"tpgzw/save_files/hundo/forest_2.bin" = "res/save_files/hundo/forest_2.bin"
"tpgzw/save_files/hundo/goats.bin" = "res/save_files/hundo/goats.bin"
"tpgzw/save_files/hundo/goats_2.bin" = "res/save_files/hundo/goats_2.bin"
"tpgzw/save_files/hundo/lakebed_bk_skip.bin" = "res/save_files/hundo/lakebed_bk_skip.bin"
"tpgzw/save_files/hundo/mdh_bridge.bin" = "res/save_files/hundo/mdh_bridge.bin"
"tpgzw/save_files/hundo/mdh_tower.bin" = "res/save_files/hundo/mdh_tower.bin"
"tpgzw/save_files/hundo/pillar_clip.bin" = "res/save_files/hundo/pillar_clip.bin"
"tpgzw/save_files/hundo/poe_1_skip.bin" = "res/save_files/hundo/poe_1_skip.bin"
"tpgzw/save_files/hundo/stallord.bin" = "res/save_files/hundo/stallord.bin"
"tpgzw/save_files/hundo/purple_mist.bin" = "res/save_files/hundo/purple_mist.bin"
"tpgzw/save_files/hundo/ordon_gate_clip.bin" = "res/save_files/hundo/ordon_gate_clip.bin"
"tpgzw/save_files/hundo/ems.bin" = "res/save_files/hundo/ems.bin"
"tpgzw/save_files/hundo/lanayru_gate_clip.bin" = "res/save_files/hundo/lanayru_gate_clip.bin"
"tpgzw/save_files/hundo/karg.bin" = "res/save_files/hundo/karg.bin"
"tpgzw/save_files/hundo/eldin_twilight.bin" = "res/save_files/hundo/eldin_twilight.bin"
"tpgzw/save_files/hundo/spr.bin" = "res/save_files/hundo/spr.bin"
"tpgzw/save_files/hundo/lakebed_1.bin" = "res/save_files/hundo/lakebed_1.bin"
"tpgzw/save_files/hundo/ag.bin" = "res/save_files/hundo/ag.bin"
"tpgzw/save_files/hundo/cits_early.bin" = "res/save_files/hundo/cits_early.bin"
"tpgzw/save_files/hundo/cits_1.bin" = "res/save_files/hundo/cits_1.bin"
"tpgzw/save_files/hundo/cits_2.bin" = "res/save_files/hundo/cits_2.bin"
"tpgzw/save_files/hundo/argorok.bin" = "res/save_files/hundo/argorok.bin"
"tpgzw/save_files/hundo/palace_1.bin" = "res/save_files/hundo/palace_1.bin"
"tpgzw/save_files/hundo/palace_2.bin" = "res/save_files/hundo/palace_2.bin"
"tpgzw/save_files/hundo/zant.bin" = "res/save_files/hundo/zant.bin"
"tpgzw/save_files/hundo/hc.bin" = "res/save_files/hundo/hc.bin"
"tpgzw/save_files/hundo/hc_tower.bin" = "res/save_files/hundo/hc_tower.bin"
"tpgzw/save_files/hundo/darkhammer.bin" = "res/save_files/hundo/darkhammer.bin"
"tpgzw/save_files/hundo/beast_ganon.bin" = "res/save_files/hundo/beast_ganon.bin"
"tpgzw/save_files/hundo/horseback_ganon.bin" = "res/save_files/hundo/horseback_ganon.bin"
"tpgzw/save_files/hundo/lanayru_twilight.bin" = "res/save_files/hundo/lanayru_twilight.bin"
"tpgzw/save_files/hundo/ookless.bin" = "res/save_files/hundo/ookless.bin"
"tpgzw/save_files/hundo/kb2.bin" = "res/save_files/hundo/kb2.bin"
"tpgzw/save_files/hundo/corotd.bin" = "res/save_files/hundo/corotd.bin"
"tpgzw/save_files/hundo/gm.bin" = "res/save_files/hundo/gm.bin"
"tpgzw/save_files/hundo/dangoro.bin" = "res/save_files/hundo/dangoro.bin"
"tpgzw/save_files/hundo/kb1.bin" = "res/save_files/hundo/kb1.bin"
"tpgzw/save_files/hundo/morpheel.bin" = "res/save_files/hundo/morpheel.bin"
"tpgzw/save_files/hundo/star_1.bin" = "res/save_files/hundo/star_1.bin"
"tpgzw/save_files/hundo/post_mdh.bin" = "res/save_files/hundo/post_mdh.bin"
"tpgzw/save_files/hundo/mountain.bin" = "res/save_files/hundo/mountain.bin"
"tpgzw/save_files/hundo/iza_1_skip.bin" = "res/save_files/hundo/iza_1_skip.bin"
"tpgzw/save_files/hundo/iza_2.bin" = "res/save_files/hundo/iza_2.bin"
"tpgzw/save_files/hundo/lh_cave.bin" = "res/save_files/hundo/lh_cave.bin"
"tpgzw/save_files/hundo/gorge_arc.bin" = "res/save_files/hundo/gorge_arc.bin"
"tpgzw/save_files/hundo/spr_superjump.bin" = "res/save_files/hundo/spr_superjump.bin"
"tpgzw/save_files/hundo/spr_bk_lja.bin" = "res/save_files/hundo/spr_bk_lja.bin"
"tpgzw/save_files/hundo/blizzeta.bin" = "res/save_files/hundo/blizzeta.bin"
"tpgzw/save_files/hundo/nf_bomb_boost.bin" = "res/save_files/hundo/nf_bomb_boost.bin"
"tpgzw/save_files/hundo/grove_2.bin" = "res/save_files/hundo/grove_2.bin"
"tpgzw/save_files/hundo/tot.bin" = "res/save_files/hundo/tot.bin"
"tpgzw/save_files/hundo/tot_early_poe.bin" = "res/save_files/hundo/tot_early_poe.bin"
"tpgzw/save_files/hundo/tot_statue_throws.bin" = "res/save_files/hundo/tot_statue_throws.bin"
"tpgzw/save_files/hundo/tot_early_hp.bin" = "res/save_files/hundo/tot_early_hp.bin"
"tpgzw/save_files/hundo/tot_darknut.bin" = "res/save_files/hundo/tot_darknut.bin"
"tpgzw/save_files/hundo/dot_skip.bin" = "res/save_files/hundo/dot_skip.bin"
"tpgzw/save_files/hundo/armogohma.bin" = "res/save_files/hundo/armogohma.bin"
"tpgzw/save_files/hundo/post_tot.bin" = "res/save_files/hundo/post_tot.bin"
"tpgzw/save_files/hundo/hotspring.bin" = "res/save_files/hundo/hotspring.bin"
"tpgzw/save_files/hundo/silver_rupee.bin" = "res/save_files/hundo/silver_rupee.bin"
"tpgzw/save_files/hundo/fbf.bin" = "res/save_files/hundo/fbf.bin"
"tpgzw/save_files/hundo/ice_puzzle.bin" = "res/save_files/hundo/ice_puzzle.bin"
"tpgzw/save_files/hundo/hv_archery.bin" = "res/save_files/hundo/hv_archery.bin"
"tpgzw/save_files/hundo/cits_poe_cycle.bin" = "res/save_files/hundo/cits_poe_cycle.bin"
"tpgzw/save_files/hundo/star_2.bin" = "res/save_files/hundo/star_2.bin"
"tpgzw/save_files/hundo/coo.bin" = "res/save_files/hundo/coo.bin"
"tpgzw/save_files/hundo/coo_10.bin" = "res/save_files/hundo/coo_10.bin"
"tpgzw/save_files/hundo/coo_20.bin" = "res/save_files/hundo/coo_20.bin"
"tpgzw/save_files/hundo/coo_30.bin" = "res/save_files/hundo/coo_30.bin"
"tpgzw/save_files/hundo/cats.bin" = "res/save_files/hundo/cats.bin"
"tpgzw/save_files/hundo/hc_darknut.bin" = "res/save_files/hundo/hc_darknut.bin"
